name: Build Mobs Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip plugin
        run: |
          zip -r MobsPlugin.zip . -x "*.git*" "*.github*" "*.md"

      - name: Upload plugin zip
        uses: actions/upload-artifact@v4
        with:
          name: MobsPlugin
          path: MobsPlugin.zip
