name: Build Mobs Plugin to PHAR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-phar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PHP and Phar tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phar-composer

      - name: Prepare plugin structure
        shell: bash
        run: |
          mkdir plugin
          shopt -s extglob
          cp -r !(plugin|.git|.github|.gitignore|README.md|LICENSE) plugin/

      - name: Generate PHAR
        run: |
          cd plugin
          phar-composer build

      - name: Upload PHAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: MobsPlugin.phar
          path: plugin/build/*.phar
